project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: CV

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    
website:
  google-analytics: "UA-XXXXXXXX"