project:
  type: website
  output-dir: docs

website:
  title: "Elin Berlin's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research


format:
  html:
    theme: minty
    css: styles.css
    toc: true